addons:
  apt:
    packages:
      - rabbitmq-server
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - celery multi start worker1 \
    -A school --pool=solo \
    --pidfile="$HOME/run/celery/school.pid" \
    --logfile="$HOME/log/celery/school.log"
  - python manage.py test
  - celery multi stopwait worker1 --pidfile="$HOME/run/celery/school.pid"
dist: xenial