services:
  - rabbitmq
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - celery -A school worker --pool=solo -l info
  - python manage.py test
dist: xenial